@extends('layouts.admin')
@section('title', 'Admission Approvals')
@section('content')
<div class="container-fluid py-4">
    <h1 class="h3 mb-3">Admission Approvals</h1>
    <form method="POST" action="{{ route('admission.approvals.request') }}" class="card mb-4">@csrf<div class="card-body row g-3 align-items-end"><div class="col-md-2"><label class="form-label">Type</label><select class="form-select" name="subject_type"><option value="lead">Lead</option><option value="applicant">Applicant</option></select></div><div class="col-md-2"><label class="form-label">Record ID</label><input name="subject_id" class="form-control" required></div><div class="col-md-2"><label class="form-label">Action</label><input name="action" class="form-control" value="bulk_status_change"></div><div class="col-md-4"><label class="form-label">After JSON</label><input name="after_json" class="form-control" value='{"priority":"high"}'></div><div class="col-md-2"><button class="btn btn-primary w-100">Request</button></div></div></form>
    <div class="card"><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>Action</th><th>Status</th><th>Reason</th><th>Requested</th><th></th></tr></thead><tbody>@forelse($approvals as $approval)<tr><td>{{ $approval->action }}</td><td>{{ $approval->status }}</td><td>{{ $approval->reason }}</td><td>{{ $approval->created_at?->diffForHumans() }}</td><td>@if($approval->status === 'pending')<div class="btn-group"><form method="POST" action="{{ route('admission.approvals.approve', $approval) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-success">Approve</button></form><form method="POST" action="{{ route('admission.approvals.reject', $approval) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-danger">Reject</button></form></div>@endif</td></tr>@empty<tr><td colspan="5" class="text-muted text-center py-3">No approvals.</td></tr>@endforelse</tbody></table></div></div>
</div>
@endsection
