@extends('layouts.admin')
@section('title', 'Admission Integrations')
@section('content')
<div class="container-fluid py-3">
<div class="d-flex justify-content-between align-items-center mb-3"><div><h3 class="fw-bold mb-1">Admission Integrations</h3><div class="text-muted small">Sandbox-ready SMS, WhatsApp, dialer, video assessment, and signature providers.</div></div><a class="btn btn-outline-success btn-sm" href="{{ route('admission.v037.exports', 'route-access') }}">Export Audit</a></div>
<div class="row g-2 mb-3">@foreach(['sms','whatsapp','dialer','video','signature'] as $channel)<div class="col-6 col-lg"><form method="POST" action="{{ route('admission.integrations.test') }}" class="card border-0 shadow-sm">@csrf<input type="hidden" name="channel" value="{{ $channel }}"><div class="card-body py-2"><div class="small text-muted">{{ strtoupper($channel) }}</div><button class="btn btn-sm btn-primary mt-1">Sandbox Test</button></div></form></div>@endforeach</div>
<div class="row g-3"><div class="col-xl-6"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-bold">Provider Status</div><div class="table-responsive"><table class="table table-sm mb-0" aria-label="Provider status"><thead><tr><th>Channel</th><th>Provider</th><th>Mode</th><th>Active</th></tr></thead><tbody>@foreach($providers as $p)<tr><td>{{ $p->channel }}</td><td>{{ $p->provider_name }}</td><td>{{ $p->sandbox_mode ? 'Sandbox' : 'Live' }}</td><td>{{ $p->is_active ? 'Yes' : 'No' }}</td></tr>@endforeach</tbody></table></div></div></div>
<div class="col-xl-6"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-bold">Webhook Events</div><div class="table-responsive"><table class="table table-sm mb-0" aria-label="Webhook events"><thead><tr><th>Provider</th><th>Event</th><th>Status</th><th>When</th></tr></thead><tbody>@forelse($webhooks as $event)<tr><td>{{ $event->provider_name }}</td><td>{{ $event->event_type }}</td><td>{{ $event->status }}</td><td>{{ $event->created_at?->diffForHumans() }}</td></tr>@empty<tr><td colspan="4" class="text-muted text-center">No webhook events.</td></tr>@endforelse</tbody></table></div></div></div></div>
<div class="card border-0 shadow-sm mt-3"><div class="card-header bg-white fw-bold">Failed Delivery Retry Queue</div><div class="table-responsive"><table class="table table-sm mb-0" aria-label="Failed communication deliveries"><thead><tr><th>Channel</th><th>Provider</th><th>Recipient</th><th>Reason</th><th></th></tr></thead><tbody>@forelse($failed as $log)<tr><td>{{ $log->channel }}</td><td>{{ $log->provider }}</td><td>{{ $log->recipient }}</td><td>{{ $log->failure_reason }}</td><td><form method="POST" action="{{ route('admission.integrations.retry', $log) }}">@csrf<button class="btn btn-sm btn-outline-primary">Retry</button></form></td></tr>@empty<tr><td colspan="5" class="text-muted text-center">No failed deliveries.</td></tr>@endforelse</tbody></table></div></div>
</div>
@endsection
