@extends('layouts.admin')
@section('title', 'PMC Approval Cockpit')
@section('content')
<div class="container-fluid py-3">
    <div class="d-flex justify-content-between align-items-start gap-2 mb-3"><div><h1 class="h4 mb-1">PMC Approval Cockpit</h1><div class="small text-muted">Curriculum, faculty, timetable, electives, assessment, student success, delivery, workload, and escalated academic approvals.</div></div>@include('academics.pmc.v004.partials.nav')</div>
    <div class="row g-2 mb-3"><div class="col-md-3"><div class="card shadow-sm"><div class="card-body py-2"><div class="small text-muted">Pending</div><div class="h4 mb-0">{{ $pending }}</div></div></div></div><div class="col-md-3"><div class="card shadow-sm"><div class="card-body py-2"><div class="small text-muted">Overdue</div><div class="h4 mb-0">{{ $overdue }}</div></div></div></div><div class="col-md-6"><div class="card shadow-sm"><div class="card-body py-2 small text-muted">Visible filter summary: {{ $filterSummary }}</div></div></div></div>
    <div class="card shadow-sm mb-3">
        <div class="card-body py-2">
            <form class="row g-2 align-items-end">
                <div class="col-md-3"><label class="form-label small">Search</label><input class="form-control form-control-sm" name="search" value="{{ request('search') }}" placeholder="Approval title or details"></div>
                <div class="col-md-2"><label class="form-label small">Status</label><select class="form-select form-select-sm" name="status"><option value="">All</option>@foreach(['pending','returned','evidence_requested','approved','rejected','escalated'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ str($status)->headline() }}</option>@endforeach</select></div>
                <div class="col-md-2"><label class="form-label small">Due</label><select class="form-select form-select-sm" name="due"><option value="">Any</option><option value="overdue" @selected(request('due')==='overdue')>Overdue</option></select></div>
                <div class="col-md-2"><label class="form-label small">Sort</label><select class="form-select form-select-sm" name="sort"><option value="due_at" @selected(request('sort','due_at')==='due_at')>Due date</option><option value="title" @selected(request('sort')==='title')>Title</option><option value="approval_type" @selected(request('sort')==='approval_type')>Type</option><option value="status" @selected(request('sort')==='status')>Status</option><option value="sla_status" @selected(request('sort')==='sla_status')>SLA</option></select></div>
                <div class="col-md-1"><label class="form-label small">Order</label><select class="form-select form-select-sm" name="direction"><option value="asc" @selected(request('direction','asc')==='asc')>Asc</option><option value="desc" @selected(request('direction')==='desc')>Desc</option></select></div>
                <div class="col-md-2 d-flex gap-1"><button class="btn btn-sm btn-primary">Filter</button><a class="btn btn-sm btn-outline-secondary" href="{{ route('academics.pmc.approvals.index') }}">Reset</a><a class="btn btn-sm btn-outline-success" href="{{ route('academics.pmc.export', ['report' => 'approvals'] + request()->query()) }}">Export</a></div>
            </form>
        </div>
    </div>
    <div class="card shadow-sm"><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>Approval</th><th>Owner</th><th>SLA</th><th>Status</th><th>Decision</th></tr></thead><tbody>@foreach($approvals as $approval)<tr><td><div class="fw-semibold">{{ $approval->title }}</div><div class="small text-muted">{{ str($approval->approval_type)->headline() }} | {{ $approval->program?->code ?? 'All programs' }}</div></td><td>{{ $approval->owner?->name ?? 'PMC' }}</td><td>{{ $approval->sla_status }} | {{ optional($approval->due_at)->format('d M') }}</td><td>{{ $approval->status }}</td><td><form method="POST" action="{{ route('academics.pmc.v004.approvals.decide', $approval) }}" class="d-flex gap-1">@csrf @method('PATCH')<select class="form-select form-select-sm" name="status"><option value="approved">approve</option><option value="returned">return</option><option value="rejected">reject</option><option value="evidence_requested">evidence</option><option value="escalated">escalate</option></select><input class="form-control form-control-sm" name="decision_reason" placeholder="Reason"><button class="btn btn-sm btn-primary">Save</button></form></td></tr>@endforeach</tbody></table></div><div class="card-footer py-2">{{ $approvals->links() }}</div></div>
</div>
@endsection
