@extends('layouts.admin')
@section('title', 'PMC Reviews, Decisions And Actions')
@section('content')
<div class="container-fluid py-3">
    <div class="d-flex justify-content-between align-items-start gap-2 mb-3"><div><h1 class="h4 mb-1">PMC Reviews, Decisions And Actions</h1><div class="small text-muted">Templates, recurring reviews, agenda, minutes, decision register, evidence, dependencies, and closure governance.</div></div>@include('academics.pmc.v004.partials.nav')</div>
    <div class="row g-3">
        <div class="col-lg-3"><div class="card shadow-sm h-100"><div class="card-header py-2 fw-semibold">Review Templates</div><div class="list-group list-group-flush">@foreach($templates as $row)<div class="list-group-item py-2"><div class="fw-semibold">{{ $row->title }}</div><div class="small text-muted">{{ $row->decision_type ?: 'template' }}</div></div>@endforeach</div></div></div>
        <div class="col-lg-9"><div class="card shadow-sm"><div class="card-header py-2 fw-semibold">Agenda Items</div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Agenda</th><th>Owner</th><th>Status</th><th>Due</th></tr></thead><tbody>@foreach($agenda as $row)<tr><td><div class="fw-semibold">{{ $row->title }}</div><div class="small text-muted">{{ $row->body }}</div></td><td>{{ $row->owner?->name ?? 'PMC' }}</td><td>{{ $row->status }}</td><td>{{ optional($row->due_at)->format('d M') }}</td></tr>@endforeach</tbody></table></div><div class="card-footer py-2">{{ $agenda->links() }}</div></div></div>
    </div>
    <div class="row g-3 mt-0">
        <div class="col-xl-6"><div class="card shadow-sm"><div class="card-header py-2 fw-semibold">Minutes Approval</div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Minutes</th><th>Status</th><th>Approve</th></tr></thead><tbody>@foreach($minutes as $row)<tr><td><div class="fw-semibold">{{ $row->title }}</div><div class="small text-muted">{{ $row->body }}</div><div class="small">{{ collect($row->evidence ?? [])->pluck('label')->join(', ') }}</div></td><td>{{ $row->status }}</td><td>@if($row->status !== 'approved')<form method="POST" action="{{ route('academics.pmc.meeting-minutes.approve', $row) }}" class="d-flex gap-1">@csrf @method('PATCH')<input class="form-control form-control-sm" name="approval_note" placeholder="Approval note"><button class="btn btn-sm btn-outline-success">Approve</button></form>@else <span class="badge text-bg-success">Approved</span>@endif</td></tr>@endforeach</tbody></table></div><div class="card-footer py-2">{{ $minutes->links() }}</div></div></div>
        <div class="col-xl-6"><div class="card shadow-sm"><div class="card-header py-2 fw-semibold">Decision Register</div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Decision</th><th>Owner</th><th>Status</th></tr></thead><tbody>@foreach($decisions as $row)<tr><td><div class="fw-semibold">{{ $row->title }}</div><div class="small text-muted">{{ $row->decision_type }}</div></td><td>{{ $row->owner?->name ?? 'PMC' }}</td><td>{{ $row->status }}</td></tr>@endforeach</tbody></table></div></div></div>
    </div>
    <div class="row g-3 mt-0">
        <div class="col-xl-7"><div class="card shadow-sm"><div class="card-header py-2 fw-semibold">Action Governance And Closure Verification</div><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>Action</th><th>Owner</th><th>Status</th><th>Evidence / Verify</th></tr></thead><tbody>@foreach($actions as $action)<tr><td><div class="fw-semibold">{{ $action->title }}</div><div class="small text-muted">{{ $action->description }}</div></td><td>{{ $action->owner?->name ?? 'PMC' }}</td><td>{{ $action->status }}<div class="small text-muted">{{ $action->severity }} | Due {{ optional($action->due_at)->format('d M') }}</div></td><td><form method="POST" action="{{ route('academics.pmc.action-governance.evidence.store', $action) }}" class="d-flex gap-1 mb-1">@csrf<input class="form-control form-control-sm" name="title" placeholder="Evidence title" required><input class="form-control form-control-sm" name="evidence_note" placeholder="Evidence note"><button class="btn btn-sm btn-outline-primary">Add Evidence</button></form><form method="POST" action="{{ route('academics.pmc.action-governance.actions.verify', $action) }}" class="d-flex gap-1">@csrf @method('PATCH')<input type="hidden" name="status" value="verified"><input class="form-control form-control-sm" name="verification_note" placeholder="Verification note"><button class="btn btn-sm btn-outline-success">Verify Close</button></form></td></tr>@endforeach</tbody></table></div><div class="card-footer py-2">{{ $actions->links() }}</div></div></div>
        <div class="col-xl-5"><div class="card shadow-sm mb-3"><div class="card-header py-2 fw-semibold">Dependencies</div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Action</th><th>Depends On</th><th>Status</th></tr></thead><tbody>@foreach($dependencies as $dependency)<tr><td>{{ $dependency->workItem?->title }}</td><td>{{ $dependency->dependsOn?->title }}</td><td>{{ $dependency->status }}</td></tr>@endforeach</tbody></table></div><div class="card-footer py-2">{{ $dependencies->links() }}</div></div><div class="card shadow-sm"><div class="card-header py-2 fw-semibold">Reminders And Escalations</div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Reminder</th><th>Owner</th><th>Due</th></tr></thead><tbody>@foreach($reminders as $reminder)<tr><td><div class="fw-semibold">{{ str($reminder->reminder_type)->headline() }}</div><div class="small text-muted">{{ $reminder->workItem?->title }}</div></td><td>{{ $reminder->owner?->name ?? 'PMC' }}</td><td>{{ $reminder->status }}<div class="small text-muted">{{ optional($reminder->due_at)->format('d M') }}</div></td></tr>@endforeach</tbody></table></div><div class="card-footer py-2">{{ $reminders->links() }}</div></div></div>
    </div>
    <div class="card shadow-sm mt-3"><div class="card-header py-2 fw-semibold">Evidence Register</div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Evidence</th><th>Action</th><th>Status</th><th>Verifier</th></tr></thead><tbody>@foreach($evidence as $item)<tr><td><div class="fw-semibold">{{ $item->title }}</div><div class="small text-muted">{{ $item->evidence_note }}</div></td><td>{{ $item->workItem?->title }}</td><td>{{ $item->verification_status }}</td><td>{{ $item->verifier?->name ?? '-' }}</td></tr>@endforeach</tbody></table></div><div class="card-footer py-2">{{ $evidence->links() }}</div></div>
</div>
@endsection
