@extends('layouts.admin')
@section('title', $title)
@section('content')
<div class="container-fluid py-3">
    <div class="d-flex justify-content-between align-items-start gap-2 mb-3"><div><h1 class="h4 mb-1">{{ $title }}</h1><div class="small text-muted">{{ $description }}</div></div>@include('academics.pmc.v004.partials.nav')</div>
    <div class="row g-2 mb-3">@foreach(['Total'=>$summary['total'],'Open'=>$summary['open'],'Critical'=>$summary['critical'],'Overdue'=>$summary['overdue']] as $label=>$value)<div class="col-6 col-md-3"><div class="card shadow-sm"><div class="card-body py-2"><div class="small text-muted">{{ $label }}</div><div class="h4 mb-0">{{ $value }}</div></div></div></div>@endforeach</div>
    <div class="card shadow-sm mb-3"><div class="card-body py-2"><form class="row g-2 align-items-end"><div class="col-md-3"><label class="form-label small">Search</label><input class="form-control form-control-sm" name="search" value="{{ request('search') }}"></div><div class="col-md-2"><label class="form-label small">Status</label><input class="form-control form-control-sm" name="status" value="{{ request('status') }}"></div><div class="col-md-2"><label class="form-label small">Risk</label><select class="form-select form-select-sm" name="risk_band"><option value="">All</option>@foreach(['low','medium','high','critical'] as $risk)<option value="{{ $risk }}" @selected(request('risk_band')===$risk)>{{ $risk }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label small">Category</label><input class="form-control form-control-sm" name="category" value="{{ request('category') }}"></div><div class="col-md-3 d-flex gap-1"><button class="btn btn-sm btn-primary">Filter</button><a class="btn btn-sm btn-outline-secondary" href="{{ url()->current() }}">Reset</a><a class="btn btn-sm btn-outline-success" href="{{ route('academics.pmc.export', $surface) }}?{{ http_build_query(request()->query()) }}">Export</a></div></form><div class="small text-muted mt-2">Visible filter summary: {{ $filterSummary }}</div></div></div>
    @if(!empty($legacyLinks))<div class="d-flex gap-2 flex-wrap mb-3">@foreach($legacyLinks as $link)<a class="btn btn-sm btn-outline-dark" href="{{ $link['route'] }}">{{ $link['label'] }}</a>@endforeach</div>@endif
    <div class="row g-3"><div class="col-xl-8"><div class="card shadow-sm"><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>Record</th><th>Owner</th><th>Status</th><th>Risk</th><th>Score</th><th>Action</th></tr></thead><tbody>@foreach($records as $record)<tr><td><div class="fw-semibold">{{ $record->title }}</div><div class="small text-muted">{{ str($record->record_type)->headline() }} | {{ $record->program?->code ?? 'All programs' }} | Due {{ optional($record->due_at)->format('d M Y') ?: 'not set' }}</div></td><td>{{ $record->owner?->name ?? 'Unassigned' }}</td><td>{{ $record->status }}</td><td>{{ $record->risk_band ?? 'normal' }}</td><td>{{ $record->score }}%</td><td><form method="POST" action="{{ route('academics.pmc.v004.records.work-item', $record) }}">@csrf<button class="btn btn-sm btn-outline-primary">Create Action</button></form></td></tr>@endforeach</tbody></table></div><div class="card-footer py-2">{{ $records->links() }}</div></div></div>
    <div class="col-xl-4"><form method="POST" action="{{ route('academics.pmc.v004.records.store') }}" class="card shadow-sm">@csrf<input type="hidden" name="record_type" value="{{ $records->first()?->record_type ?? 'planning' }}"><div class="card-header py-2 fw-semibold">Create PMC Record</div><div class="card-body vstack gap-2"><input class="form-control form-control-sm" name="title" placeholder="Title" required><input class="form-control form-control-sm" name="category" placeholder="Category"><textarea class="form-control form-control-sm" name="description" placeholder="Description"></textarea><select class="form-select form-select-sm" name="risk_band"><option value="medium">medium</option><option value="high">high</option><option value="critical">critical</option><option value="low">low</option></select><input type="date" class="form-control form-control-sm" name="due_at"><button class="btn btn-sm btn-primary">Create</button></div></form></div></div>
</div>
@endsection
