<?php

namespace Tests\Feature;

use App\Models\Student;
use App\Models\Term;
use App\Models\TermPromotion;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Spatie\Permission\Models\Role;
use Tests\TestCase;

class StudentPromotionStatusWorkflowTest extends TestCase
{
    use RefreshDatabase;

    private function makeStudent(): array
    {
        Role::firstOrCreate(['name' => 'student', 'guard_name' => 'web']);

        $user = User::factory()->create();
        $user->assignRole('student');
        $student = Student::factory()->create(['user_id' => $user->id]);

        return [$user, $student];
    }

    public function test_student_promotion_empty_state_explains_term_end_review_source(): void
    {
        [$user] = $this->makeStudent();

        $this->actingAs($user)
            ->get(route('student.promotion.index'))
            ->assertOk()
            ->assertSee('No promotion review record is available yet.')
            ->assertSee('generated by Academics or PMC after term-end results')
            ->assertSee('attendance, and required academic clearances are finalized')
            ->assertSee('contact the academic office for review status')
            ->assertDontSee('No promotion record found yet.')
            ->assertDontSee('â');
    }

    public function test_student_promotion_pending_record_uses_readable_review_fallbacks(): void
    {
        [$user, $student] = $this->makeStudent();
        $currentTerm = Term::factory()->create(['name' => 'Term Review Current']);
        $nextTerm = Term::factory()->create(['name' => 'Term Review Next']);

        TermPromotion::create([
            'student_id' => $student->id,
            'current_term_id' => $currentTerm->id,
            'promoted_to_term_id' => $nextTerm->id,
            'cgpa' => null,
            'attendance_percentage' => null,
            'meets_academic_criteria' => false,
            'meets_attendance_criteria' => false,
            'status' => 'pending',
        ]);

        $this->actingAs($user)
            ->get(route('student.promotion.index'))
            ->assertOk()
            ->assertSee('Promotion status: Pending')
            ->assertSee('Academic office review is still pending.')
            ->assertSee('Pending review')
            ->assertDontSee('â');
    }
}
