@extends('layouts.admin')
@section('title', 'Assessment Scheduling')
@section('content')
<div class="container-fluid py-3">
<div class="d-flex flex-wrap justify-content-between gap-2 mb-3"><div><h3 class="fw-bold mb-1">Assessment Scheduling</h3><div class="text-muted small">Slots, evaluator readiness, room conflicts, GD groups, and submissions.</div></div><a class="btn btn-sm btn-outline-primary" href="{{ route('admission.assessment-control-room.index') }}">Control Room</a></div>
<div class="row g-3">
<div class="col-xl-4"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-bold">Create Slot</div><div class="card-body"><form method="POST" action="{{ route('admission.assessment-slots.store') }}" class="row g-2">@csrf<div class="col-12"><label class="form-label small">Panel</label><select name="panel_id" class="form-select form-select-sm">@foreach($panels as $panel)<option value="{{ $panel->id }}">{{ $panel->name }}</option>@endforeach</select></div><div class="col-6"><label class="form-label small">Code</label><input name="slot_code" class="form-control form-control-sm" value="PGDM-{{ now()->format('Hi') }}"></div><div class="col-6"><label class="form-label small">Capacity</label><input name="capacity" type="number" value="6" class="form-control form-control-sm"></div><div class="col-6"><label class="form-label small">Start</label><input name="starts_at" type="datetime-local" class="form-control form-control-sm" value="{{ now()->addDay()->format('Y-m-d\\TH:i') }}"></div><div class="col-6"><label class="form-label small">End</label><input name="ends_at" type="datetime-local" class="form-control form-control-sm" value="{{ now()->addDay()->addHour()->format('Y-m-d\\TH:i') }}"></div><div class="col-12"><button class="btn btn-sm btn-primary">Create Slot</button></div></form></div></div></div>
<div class="col-xl-8"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-bold">Slots</div><div class="table-responsive"><table class="table table-sm mb-0" aria-label="Assessment slots"><thead><tr><th>Code</th><th>Starts</th><th>Capacity</th><th>Status</th><th>Assign</th></tr></thead><tbody>@foreach($slots as $slot)<tr><td>{{ $slot->slot_code }}</td><td>{{ $slot->starts_at }}</td><td>{{ $slot->capacity }}</td><td>{{ $slot->status }}</td><td><form method="POST" action="{{ route('admission.assessment-slots.assign') }}" class="d-flex gap-1">@csrf<input type="hidden" name="slot_id" value="{{ $slot->id }}"><input name="applicant_id" class="form-control form-control-sm" placeholder="Applicant ID"><button class="btn btn-sm btn-outline-primary">Assign</button></form></td></tr>@endforeach</tbody></table></div><div class="card-footer bg-white">{{ $slots->links() }}</div></div></div>
</div>
<div class="row g-3 mt-1">
<div class="col-xl-4"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-bold">Evaluator Invitations</div><div class="table-responsive"><table class="table table-sm mb-0" aria-label="Evaluator invitations"><thead><tr><th>Panel</th><th>User</th><th>Status</th><th></th></tr></thead><tbody>@foreach($invitations as $invite)<tr><td>{{ $invite->panel_id }}</td><td>{{ $invite->user_id }}</td><td>{{ $invite->status }}</td><td><form method="POST" action="{{ route('admission.assessment-evaluator-invitations.respond') }}">@csrf<input type="hidden" name="invitation_id" value="{{ $invite->id }}"><input type="hidden" name="status" value="accepted"><button class="btn btn-sm btn-outline-success">Accept</button></form></td></tr>@endforeach</tbody></table></div></div></div>
<div class="col-xl-4"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-bold">GD Builder</div><div class="card-body"><form method="POST" action="{{ route('admission.gd-groups.build') }}" class="row g-2">@csrf<div class="col-8"><select name="panel_id" class="form-select form-select-sm">@foreach($panels as $panel)<option value="{{ $panel->id }}">{{ $panel->name }}</option>@endforeach</select></div><div class="col-4"><input name="capacity" type="number" class="form-control form-control-sm" value="6"></div><div class="col-12"><button class="btn btn-sm btn-primary">Build Groups</button></div></form></div><div class="table-responsive"><table class="table table-sm mb-0" aria-label="GD groups"><tbody>@foreach($gdGroups as $group)<tr><td>Group {{ $group->group_number }}</td><td>{{ $group->topic }}</td><td>{{ $group->status }}</td></tr>@endforeach</tbody></table></div></div></div>
<div class="col-xl-4"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-bold">Submissions</div><div class="card-body"><form method="POST" action="{{ route('admission.assessment-submissions.store') }}" class="row g-2">@csrf<div class="col-4"><input name="applicant_id" class="form-control form-control-sm" placeholder="Applicant ID"></div><div class="col-4"><select name="submission_type" class="form-select form-select-sm"><option>case_analysis</option><option>wat</option><option>presentation</option></select></div><div class="col-4"><select name="status" class="form-select form-select-sm"><option>received</option><option>late</option><option>missing</option></select></div><div class="col-12"><input name="artifact_url" class="form-control form-control-sm" placeholder="Submission link placeholder"></div><div class="col-12"><button class="btn btn-sm btn-primary">Mark Submission</button></div></form></div></div></div>
</div>
<div class="card border-0 shadow-sm mt-3"><div class="card-header bg-white fw-bold">Resource Conflicts</div><div class="table-responsive"><table class="table table-sm mb-0" aria-label="Assessment resource conflicts"><thead><tr><th>Resource</th><th>Starts</th><th>Ends</th><th>Status</th></tr></thead><tbody>@forelse($conflicts as $conflict)<tr><td>{{ $conflict->resource_id }}</td><td>{{ $conflict->starts_at }}</td><td>{{ $conflict->ends_at }}</td><td>Conflict</td></tr>@empty<tr><td colspan="4" class="text-muted text-center">No resource conflicts.</td></tr>@endforelse</tbody></table></div></div>
</div>
@endsection
