@extends('layouts.admin')
@section('title', 'Communication Safety')
@section('content')
<div class="container-fluid py-3">
<div class="d-flex flex-wrap justify-content-between gap-2 mb-3"><div><h3 class="fw-bold mb-1">Communication Safety</h3><div class="text-muted small">Consent, quiet hours, template approvals, bulk-send preview, and sensitive audit coverage.</div></div><a class="btn btn-sm btn-outline-primary" href="{{ route('admission.communication.index') }}">Communication Hub</a></div>
<div class="row g-3">
<div class="col-xl-4"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-bold">Update Consent</div><div class="card-body"><form method="POST" action="{{ route('admission.consent-center.store') }}" class="row g-2">@csrf<div class="col-6"><select name="subject_type" class="form-select form-select-sm"><option>lead</option><option>applicant</option></select></div><div class="col-6"><input name="subject_id" class="form-control form-control-sm" placeholder="ID"></div><div class="col-6"><select name="channel" class="form-select form-select-sm"><option>sms</option><option>whatsapp</option><option>email</option><option>call</option></select></div><div class="col-6"><select name="status" class="form-select form-select-sm"><option>opt_in</option><option>opt_out</option></select></div><div class="col-12"><input name="reason" class="form-control form-control-sm" placeholder="Reason/source note"></div><div class="col-12"><button class="btn btn-sm btn-primary">Save Consent</button></div></form></div></div></div>
<div class="col-xl-4"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-bold">Template Approval</div><div class="table-responsive"><table class="table table-sm mb-0" aria-label="Template approval"><thead><tr><th>Template</th><th>Channel</th><th></th></tr></thead><tbody>@foreach($templates as $template)<tr><td>{{ $template->name }}</td><td>{{ $template->channel }}</td><td><form method="POST" action="{{ route('admission.template-approvals.request', $template->id) }}">@csrf<button class="btn btn-sm btn-outline-primary">Request</button></form></td></tr>@endforeach</tbody></table></div></div></div>
<div class="col-xl-4"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-bold">Bulk Safety Preview</div><div class="card-body"><form method="POST" action="{{ route('admission.communication-safety.preview') }}" class="row g-2">@csrf<div class="col-12"><select name="template_id" class="form-select form-select-sm">@foreach($templates as $template)<option value="{{ $template->id }}">{{ $template->name }} ({{ $template->channel }})</option>@endforeach</select></div><div class="col-12"><select name="audience" class="form-select form-select-sm"><option>leads</option><option>applicants</option></select></div><div class="col-12"><button class="btn btn-sm btn-primary">Preview Audience</button></div></form></div></div></div>
</div>
<div class="row g-3 mt-1">
<div class="col-xl-6"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-bold">Approvals</div><div class="table-responsive"><table class="table table-sm mb-0" aria-label="Template approvals"><thead><tr><th>Template</th><th>Version</th><th>Status</th><th></th></tr></thead><tbody>@foreach($approvals as $approval)<tr><td>{{ $approval->template_id }}</td><td>{{ $approval->version }}</td><td>{{ $approval->status }}</td><td>@if($approval->status !== 'approved')<form method="POST" action="{{ route('admission.template-approvals.approve', $approval->id) }}">@csrf<button class="btn btn-sm btn-outline-success">Approve</button></form>@endif</td></tr>@endforeach</tbody></table></div></div></div>
<div class="col-xl-6"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-bold">Bulk Send Previews</div><div class="table-responsive"><table class="table table-sm mb-0" aria-label="Bulk send previews"><thead><tr><th>Channel</th><th>Audience</th><th>Blocked</th><th>Duplicates</th></tr></thead><tbody>@foreach($previews as $preview)<tr><td>{{ $preview->channel }}</td><td>{{ $preview->audience_count }}</td><td>{{ $preview->blocked_count }}</td><td>{{ $preview->duplicate_count }}</td></tr>@endforeach</tbody></table></div></div></div>
</div>
<div class="row g-3 mt-1"><div class="col-xl-6"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-bold">Consent Records</div><div class="table-responsive"><table class="table table-sm mb-0" aria-label="Consent records"><thead><tr><th>Subject</th><th>Channel</th><th>Status</th><th>Reason</th></tr></thead><tbody>@foreach($consents as $consent)<tr><td>{{ class_basename($consent->subject_type) }} #{{ $consent->subject_id }}</td><td>{{ $consent->channel }}</td><td>{{ $consent->status }}</td><td>{{ Str::limit($consent->reason, 60) }}</td></tr>@endforeach</tbody></table></div></div></div><div class="col-xl-6"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-bold">Quiet Hours</div><div class="table-responsive"><table class="table table-sm mb-0" aria-label="Quiet hours"><thead><tr><th>Channel</th><th>Start</th><th>End</th><th>Emergency</th></tr></thead><tbody>@foreach($quietHours as $rule)<tr><td>{{ $rule->channel }}</td><td>{{ $rule->starts_at_time }}</td><td>{{ $rule->ends_at_time }}</td><td>{{ $rule->emergency_override_allowed ? 'Allowed' : 'Blocked' }}</td></tr>@endforeach</tbody></table></div></div></div></div>
</div>
@endsection
