@extends('layouts.admin')
@section('title', 'Integration Health')
@section('content')
<div class="container-fluid py-3">
<div class="d-flex flex-wrap justify-content-between gap-2 mb-3"><div><h3 class="fw-bold mb-1">Integration Health</h3><div class="text-muted small">Vendor-ready adapters with sandbox fallback, webhook contracts, health checks, and retry queue.</div></div><form method="POST" action="{{ route('admission.integration-health.check') }}" onsubmit="return confirm('Run integration health checks now? This will refresh provider status, credential readiness, webhook health, and retry diagnostics for Admission communication adapters.')">@csrf<button type="submit" class="btn btn-sm btn-primary">Run integration health check</button></form></div>
<div class="row g-3">
<div class="col-xl-7"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-bold">Providers</div><div class="table-responsive"><table class="table table-sm mb-0" aria-label="Integration connection list"><thead><tr><th scope="col">Channel</th><th scope="col">Provider</th><th scope="col">Mode</th><th scope="col">Credential Keys</th></tr></thead><tbody>@foreach($providers as $provider)<tr><td>{{ $provider->channel }}</td><td>{{ $provider->provider_name }}</td><td>{{ $provider->sandbox_mode ? 'Sandbox' : 'Live' }}</td><td class="small">{{ implode(', ', json_decode($provider->credential_keys ?: '[]', true) ?: []) }}</td></tr>@endforeach</tbody></table></div></div></div>
<div class="col-xl-5"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-bold">Adapter Docs</div><div class="table-responsive"><table class="table table-sm mb-0" aria-label="Adapter documentation"><thead><tr><th scope="col">Channel</th><th scope="col">Live Adapter</th><th scope="col">Webhook</th></tr></thead><tbody>@foreach($docs as $channel => $doc)<tr><td>{{ $channel }}</td><td>{{ $doc['live'] }}</td><td class="small">/admission/integration-webhooks/{{ $doc['sandbox'] }}</td></tr>@endforeach</tbody></table></div></div></div>
</div>
<div class="row g-3 mt-1"><div class="col-xl-6"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-bold">Health Checks</div><div class="table-responsive"><table class="table table-sm mb-0" aria-label="Integration health checks"><thead><tr><th scope="col">Provider</th><th scope="col">Status</th><th scope="col">Credentials</th><th scope="col">Checked</th></tr></thead><tbody>@foreach($health as $row)<tr><td>{{ $row->provider_id }}</td><td>{{ $row->status }}</td><td>{{ $row->credentials_present ? 'Present' : 'Missing/sandbox' }}</td><td>{{ $row->checked_at }}</td></tr>@endforeach</tbody></table></div></div></div><div class="col-xl-6"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-bold">Retry Queue</div><div class="table-responsive"><table class="table table-sm mb-0" aria-label="Integration retry queue"><thead><tr><th scope="col">Channel</th><th scope="col">Provider</th><th scope="col">Status</th><th aria-label="Actions" scope="col"></th></tr></thead><tbody>@foreach($retries as $retry)<tr><td>{{ $retry->channel }}</td><td>{{ $retry->provider_name }}</td><td>{{ $retry->status }} ({{ $retry->attempts }}/{{ $retry->max_attempts }})</td><td><form method="POST" action="{{ route('admission.integration-health.retry', $retry->id) }}" onsubmit="return confirm('Retry this integration job? Confirm the provider is healthy enough and the applicant communication or webhook payload will not be duplicated incorrectly.')">@csrf<button type="submit" class="btn btn-sm btn-outline-primary">Retry integration job</button></form></td></tr>@endforeach</tbody></table></div></div></div></div>
</div>
@endsection
