@extends('layouts.admin')
@section('title', 'Integration Health')
@section('content')
<div class="container-fluid py-3">
<div class="d-flex flex-wrap justify-content-between gap-2 mb-3"><div><h3 class="fw-bold mb-1">Integration Health</h3><div class="text-muted small">Vendor-ready adapters with sandbox fallback, webhook contracts, health checks, and retry queue.</div></div><form method="POST" action="{{ route('admission.integration-health.check') }}">@csrf<button class="btn btn-sm btn-primary">Run Health Check</button></form></div>
<div class="row g-3">
<div class="col-xl-7"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-bold">Providers</div><div class="table-responsive"><table class="table table-sm mb-0" aria-label="Integration providers"><thead><tr><th>Channel</th><th>Provider</th><th>Mode</th><th>Credential Keys</th></tr></thead><tbody>@foreach($providers as $provider)<tr><td>{{ $provider->channel }}</td><td>{{ $provider->provider_name }}</td><td>{{ $provider->sandbox_mode ? 'Sandbox' : 'Live' }}</td><td class="small">{{ implode(', ', json_decode($provider->credential_keys ?: '[]', true) ?: []) }}</td></tr>@endforeach</tbody></table></div></div></div>
<div class="col-xl-5"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-bold">Adapter Docs</div><div class="table-responsive"><table class="table table-sm mb-0" aria-label="Adapter documentation"><thead><tr><th>Channel</th><th>Live Adapter</th><th>Webhook</th></tr></thead><tbody>@foreach($docs as $channel => $doc)<tr><td>{{ $channel }}</td><td>{{ $doc['live'] }}</td><td class="small">/admission/integration-webhooks/{{ $doc['sandbox'] }}</td></tr>@endforeach</tbody></table></div></div></div>
</div>
<div class="row g-3 mt-1"><div class="col-xl-6"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-bold">Health Checks</div><div class="table-responsive"><table class="table table-sm mb-0" aria-label="Integration health checks"><thead><tr><th>Provider</th><th>Status</th><th>Credentials</th><th>Checked</th></tr></thead><tbody>@foreach($health as $row)<tr><td>{{ $row->provider_id }}</td><td>{{ $row->status }}</td><td>{{ $row->credentials_present ? 'Present' : 'Missing/sandbox' }}</td><td>{{ $row->checked_at }}</td></tr>@endforeach</tbody></table></div></div></div><div class="col-xl-6"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-bold">Retry Queue</div><div class="table-responsive"><table class="table table-sm mb-0" aria-label="Integration retry queue"><thead><tr><th>Channel</th><th>Provider</th><th>Status</th><th></th></tr></thead><tbody>@foreach($retries as $retry)<tr><td>{{ $retry->channel }}</td><td>{{ $retry->provider_name }}</td><td>{{ $retry->status }} ({{ $retry->attempts }}/{{ $retry->max_attempts }})</td><td><form method="POST" action="{{ route('admission.integration-health.retry', $retry->id) }}">@csrf<button class="btn btn-sm btn-outline-primary">Retry</button></form></td></tr>@endforeach</tbody></table></div></div></div></div>
</div>
@endsection
