@extends('layouts.admin')
@section('title', 'Offer And Seat Control')
@section('content')
<div class="container-fluid py-3">
<div class="d-flex flex-wrap justify-content-between gap-2 mb-3"><div><h3 class="fw-bold mb-1">Offer And Seat Control</h3><div class="text-muted small">Offer rounds, waitlist movement, seat holds, deferrals, and joining-kit readiness.</div></div><a class="btn btn-sm btn-outline-primary" href="{{ route('admission.offer-letters.index', $programs->first()) }}">Offer Letters</a></div>
<div class="row g-3">
<div class="col-xl-4"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-bold">Create Offer Round</div><div class="card-body"><form method="POST" action="{{ route('admission.offer-rounds.store') }}" class="row g-2">@csrf<div class="col-6"><select name="program_id" class="form-select form-select-sm">@foreach($programs as $program)<option value="{{ $program->id }}">{{ $program->name }}</option>@endforeach</select></div><div class="col-6"><select name="batch_id" class="form-select form-select-sm">@foreach($batches as $batch)<option value="{{ $batch->id }}">{{ $batch->name }}</option>@endforeach</select></div><div class="col-4"><input name="round_number" type="number" value="1" class="form-control form-control-sm"></div><div class="col-8"><input name="name" value="Round {{ now()->format('M d') }}" class="form-control form-control-sm"></div><div class="col-12"><input name="offer_valid_until" type="datetime-local" value="{{ now()->addDays(7)->format('Y-m-d\\TH:i') }}" class="form-control form-control-sm"></div><div class="col-12"><button class="btn btn-sm btn-primary">Create Round</button></div></form></div></div></div>
<div class="col-xl-8"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-bold">Offer Rounds</div><div class="table-responsive"><table class="table table-sm mb-0" aria-label="Offer rounds"><thead><tr><th>Round</th><th>Status</th><th>Valid Until</th><th></th></tr></thead><tbody>@foreach($rounds as $round)<tr><td>{{ $round->name }}</td><td>{{ $round->status }}</td><td>{{ $round->offer_valid_until }}</td><td><form method="POST" action="{{ route('admission.offer-rounds.publish', $round->id) }}">@csrf<button class="btn btn-sm btn-outline-success">Publish</button></form></td></tr>@endforeach</tbody></table></div><div class="card-footer bg-white">{{ $rounds->links() }}</div></div></div>
</div>
<div class="row g-3 mt-1">
<div class="col-xl-4"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-bold">Waitlist</div><div class="card-body py-2"><form method="POST" action="{{ route('admission.waitlist.store') }}" class="d-flex gap-1">@csrf<input name="applicant_id" class="form-control form-control-sm" placeholder="Applicant ID"><input name="rank" type="number" class="form-control form-control-sm" value="1"><button class="btn btn-sm btn-primary">Add</button></form></div><div class="table-responsive"><table class="table table-sm mb-0" aria-label="Waitlist entries"><tbody>@foreach($waitlist as $entry)<tr><td>#{{ $entry->rank }}</td><td>Applicant {{ $entry->applicant_id }}</td><td>{{ $entry->status }}</td></tr>@endforeach</tbody></table></div></div></div>
<div class="col-xl-4"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-bold">Seat Holds</div><div class="table-responsive"><table class="table table-sm mb-0" aria-label="Seat holds"><thead><tr><th>Applicant</th><th>Status</th><th>Expires</th><th></th></tr></thead><tbody>@foreach($holds as $hold)<tr><td>{{ $hold->applicant_id }}</td><td>{{ $hold->status }}</td><td>{{ $hold->expires_at }}</td><td>@if($hold->status === 'held')<form method="POST" action="{{ route('admission.seat-control.release', $hold->id) }}">@csrf<input type="hidden" name="reason" value="Manual release from seat control"><button class="btn btn-sm btn-outline-danger">Release</button></form>@endif</td></tr>@endforeach</tbody></table></div></div></div>
<div class="col-xl-4"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-bold">Deferrals And Joining Kit</div><div class="card-body py-2"><form method="POST" action="{{ route('admission.deferrals.store') }}" class="row g-1">@csrf<input name="applicant_id" class="form-control form-control-sm" placeholder="Applicant ID"><select name="to_batch_id" class="form-select form-select-sm">@foreach($batches as $batch)<option value="{{ $batch->id }}">{{ $batch->name }}</option>@endforeach</select><input name="reason" class="form-control form-control-sm" value="Applicant requested future batch"><button class="btn btn-sm btn-primary">Request Deferral</button></form></div><div class="table-responsive"><table class="table table-sm mb-0" aria-label="Joining kit tasks"><tbody>@foreach($joiningTasks as $task)<tr><td>{{ $task->title }}</td><td>{{ $task->status }}</td><td>Applicant {{ $task->applicant_id }}</td></tr>@endforeach</tbody></table></div></div></div>
</div>
</div>
@endsection
