@extends('layouts.admin')
@section('title', 'PMC Curriculum Governance')
@section('content')
<div class="container-fluid py-3">
    <div class="d-flex justify-content-between align-items-center gap-2 mb-3"><div><h1 class="h4 mb-1">PMC Curriculum Governance</h1><div class="small text-muted">Program structure, syllabus/version rollout, credits, OBE mapping, approval lifecycle, and compliance checks.</div></div><div class="d-flex gap-2 align-items-center">@include('academics.pmc.v003.partials.nav')<form method="POST" action="{{ route('academics.pmc.curriculum-validations.refresh') }}">@csrf<button class="btn btn-sm btn-primary">Refresh Validations</button></form></div></div>
    <div class="row g-2 mb-3"><div class="col-md-4"><div class="card shadow-sm"><div class="card-body py-2"><div class="small text-muted">Pending Approval</div><div class="h4 mb-0">{{ $pending_approval }}</div></div></div></div><div class="col-md-4"><div class="card shadow-sm"><div class="card-body py-2"><div class="small text-muted">Rollout Due</div><div class="h4 mb-0">{{ $rollout_due }}</div></div></div></div><div class="col-md-4"><div class="card shadow-sm"><div class="card-body py-2"><div class="small text-muted">Validation Blockers</div><div class="h4 mb-0">{{ $validation_blockers }}</div></div></div></div></div>
    <div class="card shadow-sm"><div class="card-header py-2 small text-muted">Visible filter summary: active curriculum plans | <a href="{{ route('academics.pmc.export', 'curriculum') }}">Export current view</a></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Plan</th><th>Program</th><th>Owner</th><th>Approval</th><th>Score</th><th>Due</th></tr></thead><tbody>@foreach($plans as $plan)<tr><td>{{ $plan->title }}</td><td>{{ $plan->program?->code ?? '-' }}</td><td>{{ $plan->owner?->name ?? 'Unassigned' }}</td><td>{{ $plan->approval_status }}</td><td>{{ $plan->readiness_score }}%</td><td>{{ optional($plan->rollout_due_at)->format('d M Y') }}</td></tr>@endforeach</tbody></table></div><div class="card-footer py-2">{{ $plans->links() }}</div></div>
    <div class="card shadow-sm mt-3"><div class="card-header py-2 fw-semibold">Curriculum Validation Control</div><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>Check</th><th>Subject</th><th>Status</th><th>Score</th><th>Owner</th><th>Due</th><th>Recommended Action</th></tr></thead><tbody>@forelse($validations as $validation)<tr><td><div class="fw-semibold">{{ $validation->title }}</div><div class="small text-muted">{{ str($validation->validation_type)->headline() }} | {{ $validation->curriculumPlan?->title }}</div></td><td>{{ $validation->subject?->code ?? 'Plan level' }}</td><td>{{ $validation->status }}<div class="small text-muted">{{ $validation->severity }}</div></td><td>{{ $validation->score }}%</td><td>{{ $validation->owner?->name ?? 'PMC' }}</td><td>{{ optional($validation->due_at)->format('d M Y') ?: '-' }}</td><td class="small">{{ $validation->recommended_action }}</td></tr>@empty<tr><td colspan="7" class="text-muted">No curriculum validations yet. Refresh validations to generate syllabus, credit, CO, mapping, and rollout checks.</td></tr>@endforelse</tbody></table></div><div class="card-footer py-2">{{ $validations->links() }}</div></div>
</div>
@endsection
