@extends('layouts.admin')
@section('title', 'PMC Reviews')
@section('content')
<div class="container-fluid py-3">
    <div class="d-flex justify-content-between align-items-center gap-2 mb-3"><div><h1 class="h4 mb-1">PMC Reviews And Actions</h1><div class="small text-muted">Review meetings, minutes, decisions, ownership, and closure tracking for PMC operations.</div></div>@include('academics.pmc.v003.partials.nav')</div>
    <div class="row g-3"><div class="col-lg-4"><form method="POST" action="{{ route('academics.pmc.reviews.store') }}" class="card shadow-sm">@csrf<div class="card-header py-2 fw-semibold">Create Review</div><div class="card-body vstack gap-2"><input aria-label="Review title" class="form-control form-control-sm" name="title" placeholder="Review title" required><select aria-label="Review Type" class="form-select form-select-sm" name="review_type"><option value="weekly_pmc">Weekly PMC</option><option value="curriculum_review">Curriculum Review</option><option value="faculty_review">Faculty Review</option><option value="timetable_review">Timetable Review</option><option value="student_success_review">Student Success Review</option></select><input aria-label="Scheduled For" type="datetime-local" class="form-control form-control-sm" name="scheduled_for"><textarea aria-label="Agenda" class="form-control form-control-sm" name="agenda" placeholder="Agenda"></textarea><button class="btn btn-sm btn-primary">Create</button></div></form></div>
    <div class="col-lg-8"><div class="card shadow-sm"><div class="card-header py-2 fw-semibold">Meetings</div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th scope="col">Meeting</th><th scope="col">Type</th><th scope="col">Chair</th><th scope="col">Status</th><th scope="col">Schedule</th></tr></thead><tbody>@foreach($meetings as $meeting)<tr><td>{{ $meeting->title }}</td><td>{{ $meeting->review_type }}</td><td>{{ $meeting->chair?->name ?? 'PMC' }}</td><td>{{ $meeting->status }}</td><td>{{ optional($meeting->scheduled_for)->format('d M Y H:i') }}</td></tr>@endforeach</tbody></table></div><div class="card-footer py-2">{{ $meetings->links() }}</div></div></div></div>
</div>
@endsection
