@extends('layouts.admin')
@section('title', 'PMC Workbench')
@section('content')
<div class="container-fluid py-3">
    <div class="d-flex justify-content-between align-items-center gap-2 mb-3"><div><h1 class="h4 mb-1">PMC Workbench</h1><div class="small text-muted">Role-scoped action queue with owners, due dates, status, escalation, and closure tracking.</div></div>@include('academics.pmc.v003.partials.nav')</div>
    <div class="row g-2 mb-3">@foreach(['Open'=>$open,'Overdue'=>$overdue,'Critical'=>$critical] as $label=>$value)<div class="col-md-4"><div class="card shadow-sm"><div class="card-body py-2"><div class="small text-muted">{{ $label }}</div><div class="h4 mb-0">{{ $value }}</div></div></div></div>@endforeach</div>
    <div class="row g-3"><div class="col-lg-4"><form method="POST" action="{{ route('academics.pmc.work-items.store') }}" class="card shadow-sm">@csrf<div class="card-header py-2 fw-semibold">Create Work Item</div><div class="card-body vstack gap-2"><select aria-label="Work Type" class="form-select form-select-sm" name="work_type"><option value="curriculum">Curriculum</option><option value="faculty">Faculty</option><option value="timetable">Timetable</option><option value="student_success">Student Success</option><option value="review_action">Review Action</option></select><input aria-label="Work title" class="form-control form-control-sm" name="title" placeholder="Work title" required><select aria-label="Priority" class="form-select form-select-sm" name="priority"><option>normal</option><option>high</option><option>critical</option></select><input aria-label="Due At" type="date" class="form-control form-control-sm" name="due_at"><button class="btn btn-sm btn-primary">Create</button></div></form></div>
    <div class="col-lg-8"><div class="card shadow-sm"><div class="card-header py-2 small text-muted">Visible filter summary: type={{ $type }} | sort=latest | <a href="{{ route('academics.pmc.export', 'workbench') }}">Export current view</a></div><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th scope="col">Item</th><th scope="col">Owner</th><th scope="col">Status</th><th scope="col">Update</th></tr></thead><tbody>@foreach($items as $item)<tr><td><div class="fw-semibold">{{ $item->title }}</div><div class="small text-muted">{{ $item->description ?: str_replace('_',' ', $item->work_type) }}</div></td><td>{{ $item->owner?->name ?? 'Unassigned' }}</td><td>{{ $item->status }}</td><td><form method="POST" action="{{ route('academics.pmc.work-items.update', $item) }}" class="d-flex gap-1">@csrf @method('PATCH')<input type="hidden" name="priority" value="{{ $item->priority }}"><input type="hidden" name="severity" value="{{ $item->severity }}"><select aria-label="Status" name="status" class="form-select form-select-sm"><option value="open">open</option><option value="in_progress">in_progress</option><option value="done">done</option><option value="blocked">blocked</option></select><button class="btn btn-sm btn-outline-primary">Save work item</button></form></td></tr>@endforeach</tbody></table></div><div class="card-footer py-2">{{ $items->links() }}</div></div></div></div>
</div>
@endsection
