@extends('layouts.admin')
@section('title', 'Dean Action Governance')
@section('content')
<div class="container-fluid py-3">
    <div class="d-flex justify-content-between align-items-center gap-2 mb-3"><div><h1 class="h4 mb-1">Advanced Action Governance</h1><div class="small text-muted">Escalations, reminders, dependencies, evidence, and closure verification.</div></div>@include('academics.dean-os.partials.nav')</div>
    <div class="row g-2 mb-3">@foreach(['Overdue'=>$overdue,'Blocked'=>$blocked,'Evidence Pending'=>$evidence_pending] as $label=>$value)<div class="col-md-4"><div class="card shadow-sm"><div class="card-body py-2"><div class="small text-muted">{{ $label }}</div><div class="h4 mb-0">{{ $value }}</div></div></div></div>@endforeach</div>
    <div class="card shadow-sm"><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th scope="col">Action</th><th scope="col">Owner</th><th scope="col">Priority</th><th scope="col">Status</th><th scope="col">Evidence</th></tr></thead><tbody>@foreach($actions as $action)<tr><td>{{ $action->title }}</td><td>{{ $action->owner?->name ?? 'Unassigned' }}</td><td>{{ $action->priority }}</td><td>{{ $action->status }}</td><td><form method="POST" action="{{ route('academics.dean-os.action-evidence.store', $action) }}" class="d-flex gap-1">@csrf<input aria-label="Evidence title" class="form-control form-control-sm" name="title" placeholder="Evidence title" required><button class="btn btn-sm btn-outline-primary" onclick="return confirm('Attach this evidence to the Dean action item? Confirm evidence title, action owner, closure expectation, and audit visibility before adding it.')">Add evidence</button></form></td></tr>@endforeach</tbody></table></div><div class="card-footer py-2">{{ $actions->links() }}</div></div>
</div>
@endsection
